# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# Environments
.venv/
venv/
ENV/

# Data and Models (Keep these local, track with DVC if needed)
data/raw/*
data/processed/*
models/*.pkl
models/*.h5

# Jupyter Notebook checkpoints
.ipynb_checkpoints/